spring:
  application:
    name: library

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  cache:
    type: redis
    redis:
      time-to-live: 60m
      cache-null-values: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 1
      timeout: 5000

logging:
  level:
    org.springframework.cache: TRACE

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:a00472b2335efa1d4f5e381f3d262e2f9648cf62ee8f0e689842bb2ef0d6d2ab}
      expiration: ${JWT_KEY_EXPIRATION:3600000}


