spring:
  application:
    name: library

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  cache:
    type: redis
    redis:
      time-to-live: 60m
      cache-null-values: false

  data:
    redis:
      host: localhost
      port: 6379
      database: 1
      password: redis
      timeout: 5000


